export const DISCUSSION_LIST_REQUEST = 'DISCUSSION_LIST_REQUEST'
export const DISCUSSION_LIST_SUCCESS = 'DISCUSSION_LIST_SUCCESS'
export const DISCUSSION_LIST_FAIL = 'DISCUSSION_LIST_FAIL'

export const DISCUSSION_CREATE_REQUEST = 'DISCUSSION_CREATE_REQUEST'
export const DISCUSSION_CREATE_SUCCESS = 'DISCUSSION_CREATE_SUCCESS'
export const DISCUSSION_CREATE_FAIL = 'DISCUSSION_CREATE_FAIL'
export const DISCUSSION_CREATE_RESET = "DISCUSSION_CREATE_RESET"


export const D_LIST_REQUEST = 'D_LIST_REQUEST'
export const D_LIST_SUCCESS = 'D_LIST_SUCCESS'
export const D_LIST_FAIL = 'D_LIST_FAIL'
export const D_LIST_RESET= "D_LIST_RESET"

export const D_REPLY_REQUEST = 'D_REPLY_REQUEST'
export const D_REPLY_SUCCESS = 'D_REPLY_SUCCESS'
export const D_REPLY_FAIL = 'D_REPLY_FAIL'
export const D_REPLY_RESET= "D_REPLY_RESET"